[build]
  base = "."
  command = "bun install && bun --cwd storage/framework/views/web run build"
  publish = "storage/framework/views/web/dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 