[build]
  base = "."
  command = "bun install && ./buddy build views"
  publish = "storage/framework/views/web/dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 