[build]
  base = "/"
  command = "bun install && touch .env && cd storage/framework/core && bun run build && cd ../../.. && ./buddy build views"
  publish = "storage/framework/views/web/dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 