/**
 * Walks app/Models/**​/*.ts and emits resources/types/user-models.d.ts
 * declaring every file's default export as an ambient global. Makes
 * `Judge.all()` / `CourtHouse.where(...)` etc. type-check in actions
 * without forcing per-file `import Judge from '~/app/Models/Judge'`.
 *
 * The framework's own `storage/framework/types/auto-imports.d.ts` only
 * declares a handful of framework-default models as globals — it never
 * picks up user models in app/Models/. This generator fills that gap
 * with a project-owned d.ts so a framework regen can't wipe it.
 *
 * Re-run after adding a new model file:
 *   bun run scripts/generate-user-model-types.ts
 */

import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'

const PROJECT_ROOT = resolve(import.meta.dir, '..')
const MODELS_ROOT = join(PROJECT_ROOT, 'app', 'Models')
const OUT_PATH = join(PROJECT_ROOT, 'resources', 'types', 'user-models.d.ts')

interface ModelEntry {
  name: string
  // Path relative to the directory holding the d.ts (no .ts extension)
  importPath: string
}

function walk(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const st = statSync(full)
    if (st.isDirectory()) {
      // Skip nested node_modules / hidden dirs defensively.
      if (entry === 'node_modules' || entry.startsWith('.')) continue
      out.push(...walk(full))
      continue
    }
    if (!st.isFile()) continue
    if (!entry.endsWith('.ts')) continue
    if (entry === 'index.ts') continue
    out.push(full)
  }
  return out
}

function pascalNameFromFile(absPath: string): string {
  const base = absPath.substring(absPath.lastIndexOf('/') + 1).replace(/\.ts$/, '')
  return base
}

function buildEntries(): ModelEntry[] {
  const outDir = dirname(OUT_PATH)
  const files = walk(MODELS_ROOT).sort()
  const seen = new Set<string>()
  const entries: ModelEntry[] = []

  for (const abs of files) {
    const name = pascalNameFromFile(abs)
    // Skip non-Pascal-cased filenames (helpers, README handled by .ts filter).
    if (!/^[A-Z][A-Za-z0-9]+$/.test(name)) continue

    // Skip duplicates — when a model exists in BOTH the top-level
    // app/Models AND a subdir like app/Models/commerce/, prefer the
    // top-level path (sorted alphabetically, top-level wins on tie
    // because its path is shorter).
    if (seen.has(name)) continue
    seen.add(name)

    let rel = relative(outDir, abs).replace(/\.ts$/, '')
    if (!rel.startsWith('.')) rel = `./${rel}`
    entries.push({ name, importPath: rel })
  }

  return entries
}

function render(entries: ModelEntry[]): string {
  const banner = `// AUTO-GENERATED by scripts/generate-user-model-types.ts — do not edit.
// Walks app/Models/**/*.ts and declares each default export as an
// ambient global so actions can use Judge.all() / User.where(...)
// without explicit per-file imports. Re-run after adding a new model.
//
// Each model is typed as the BenchModel interface (a hand-rolled
// minimal surface over bqb's query builder) rather than
// "typeof import('./Judge').default" because defineModel's return
// is cast to Record<string, unknown> in storage/framework/core/orm
// — so the static import form gives "unknown" on every chained call.
// BenchModel mirrors the runtime API and unblocks IDE autocomplete;
// the trade-off is per-attribute typing on result rows is lost.
// File upstream when bandwidth allows: have defineModel return the
// bqb createModel result instead of Record<string, unknown>.

`

  const ifaceBlock = `interface BenchModelStatic {
  all: () => Promise<any[]>
  first: () => Promise<any | null>
  find: (id: number | string) => Promise<any | null>
  findOrFail: (id: number | string) => Promise<any>
  where: (...args: any[]) => BenchModelQuery
  whereIn: (col: string, values: any[]) => BenchModelQuery
  whereNotIn: (col: string, values: any[]) => BenchModelQuery
  whereNull: (col: string) => BenchModelQuery
  whereNotNull: (col: string) => BenchModelQuery
  orderBy: (col: string, dir?: 'asc' | 'desc') => BenchModelQuery
  limit: (n: number) => BenchModelQuery
  offset: (n: number) => BenchModelQuery
  with: (...rels: string[]) => BenchModelQuery
  query: () => BenchModelQuery
  count: () => Promise<number>
  exists: (...args: any[]) => Promise<boolean>
  create: (data: Record<string, any>) => Promise<any>
  firstOrCreate: (lookup: Record<string, any>, attrs?: Record<string, any>) => Promise<any>
  updateOrCreate: (lookup: Record<string, any>, attrs: Record<string, any>) => Promise<any>
  update: (id: number | string, data: Record<string, any>) => Promise<any>
  delete: (id?: number | string) => Promise<any>
  withoutEvents: <T>(fn: () => Promise<T> | T) => Promise<T>
}
interface BenchModelQuery extends BenchModelStatic {
  get: () => Promise<any[]>
  execute: () => Promise<any[]>
  toSQL: () => string
}

`

  const lines = entries.map(e =>
    `  const ${e.name}: BenchModelStatic`,
  )

  return `${banner}${ifaceBlock}declare global {\n${lines.join('\n')}\n}\n\nexport {}\n`
}

const entries = buildEntries()
const out = render(entries)
writeFileSync(OUT_PATH, out, 'utf8')

console.log(`Wrote ${OUT_PATH}`)
console.log(`  ${entries.length} model${entries.length === 1 ? '' : 's'} declared`)
for (const e of entries) console.log(`  - ${e.name}`)
